import {
  ArrowLeft,
  ArrowRight,
  ChevronDown,
  Columns2,
  ChevronUp,
  Command,
  FileText,
  Focus,
  FolderOpen,
  Highlighter,
  Keyboard,
  MoveHorizontal,
  NotebookPen,
  PanelLeft,
  PanelRight,
  Plus,
  Redo2,
  SquareDashed,
  StickyNote,
  Tags,
  Trash,
  TriangleAlert,
  Undo2,
  X,
  ZoomIn,
  ZoomOut,
  Search,
  type LucideIcon,
} from "lucide-react";

// Commands refer to icons by name so the registry stays free of UI imports.
const ICONS: Record<string, LucideIcon> = {
  open: FolderOpen,
  close: X,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
  palette: Command,
  keyboard: Keyboard,
  file: FileText,
  outline: PanelLeft,
  "fit-width": MoveHorizontal,
  search: Search,
  highlight: Highlighter,
  area: SquareDashed,
  annotations: PanelRight,
  undo: Undo2,
  redo: Redo2,
  categories: Tags,
  note: StickyNote,
  delete: Trash,
  warning: TriangleAlert,
  up: ChevronUp,
  down: ChevronDown,
  add: Plus,
  export: NotebookPen,
  focus: Focus,
  back: ArrowLeft,
  split: Columns2,
  forward: ArrowRight,
};

export function Icon({ name, size = 18 }: { name: string; size?: number }) {
  const Component = ICONS[name] ?? FileText;
  return <Component size={size} aria-hidden="true" strokeWidth={1.75} />;
}
